package nl.hackyourfuture.project.backend.user.dto;
import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.project.backend.user.User;

import java.util.UUID;

@Schema(description = "A user account as returned by the API")
public record UserResponse(
        @Schema(
                description = "Unique identifier of the user, generated by the server",
                example = "effe1126-329f-4f31-942c-31bc0be4d672",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        UUID id,
        @Schema(
                description = "Email address of the user",
                example = "user@example.com",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String email
) {
    public static UserResponse from(User user) {
        return new UserResponse(
                user.getId(),
                user.getEmail()
        );
    }
}
