spring:
  application:
    name: hyf-project-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}

server:
  port: ${PORT:8080}

# API Docs
springdoc:
  api-docs:
    path: /api/docs/openapi.yaml
scalar:
  enabled: true
  path: /api/docs

