spring:
  application:
    name: hyf-project-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/project_db?currentSchema=app}
    username: ${DB_USER:app_user}
    password: ${DB_PASSWORD:secret}
  flyway:
    schemas: app

server:
  port: ${PORT:8080}

# API Docs
springdoc:
  api-docs:
    path: /api/docs/openapi.yaml
scalar:
  enabled: true
  path: /api/docs
  url: ${springdoc.api-docs.path}

