spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    schemas: ${DB_SCHEMA}

logging:
  level:
    root: INFO

# Add any additional configuration for the production environment